FROM python:3.12.3
WORKDIR /frontend_app

COPY __init__.py ./__init__.py
COPY http_verbs.py ./http_verbs.py
COPY Introduction.py ./Introduction.py
COPY pages/1_Data_Visualisation.py ./pages/1_Data_Visualisation.py
COPY pages/2_Model_Information.py ./pages/2_Model_Information.py
COPY frontend_requirements.txt ./frontend_requirements.txt
RUN pip3 install -r frontend_requirements.txt
COPY . .
CMD streamlit run --server.port $PORT Introduction.py