FROM python:3.12.3
WORKDIR /api_app

COPY stratapi.py ./stratapi.py
COPY stratdata.db ./stratdata.db
COPY api_requirements.txt ./api_requirements.txt
RUN pip3 install -r api_requirements.txt
COPY . .
CMD [ "sh", "-c", "uvicorn stratapi:api_app --host=0.0.0.0 --port=$PORT" ]