name: Build Docker image and deploy to Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
      - name: Login to Heroku Container registry
        run: heroku container:login  
      - name: Switch stacks
        run: heroku stack:set container -a stratview
      - name: Build and push
        run: heroku container:push -a stratview web
      - name: Release
        run: heroku container:release -a stratview web  